NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org.lead.merchant-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org.lead.merchant-cert.pem
    OrganizationalUnitIdentifier: peer
