name: upaayan-loyalty-LeadMerchant
x-type: hlfv1
description: Loyalty Points Network
version: '1.0'
channels:
    common:
        orderers:
            - orderer0.ordererauthority.organizations
        peers:
            peer0.org.lead.merchant:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQeury: true
                eventSource: true
            peer0.org.redeem.merchant.one:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQeury: true
                eventSource: true
            peer0.org.issue.merchant.two:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQeury: true
                eventSource: true
            peer0.org.issueandredeem.merchant.three:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQeury: true
                eventSource: true
organizations:
    LeadMerchant:
        mspid: LeadMerchantMSP
        peers:
            - peer0.org.lead.merchant
        certificateAuthorities:
            - ca-LeadMerchant
        adminPrivateKey:
            path: artifacts/channel/crypto-config/peerOrganizations/org.lead.merchant/users/Admin@org.lead.merchant/msp/keystore/a66c2e92a10dd917400734780b0721e8d25ed2cbf825bfc67da74707b771e02d_sk
        signedCert:
            path: artifacts/channel/crypto-config/peerOrganizations/org.lead.merchant/users/Admin@org.lead.merchant/msp/signcerts/Admin@org.lead.merchant-cert.pem
    Merchant1:
        mspid: Merchant1MSP
        peers:
            - peer0.org.redeem.merchant.one
        certificateAuthorities:
            - ca-Merchant1
        adminPrivateKey:
            path: artifacts/channel/crypto-config/peerOrganizations/org.redeem.merchant.one/users/Admin@org.redeem.merchant.one/msp/keystore/381fd6640d21b5c1f29bdd37d0558009d73ecec00e9ea5323af26350da87f244_sk
        signedCert:
            path: artifacts/channel/crypto-config/peerOrganizations/org.redeem.merchant.one/users/Admin@org.redeem.merchant.one/msp/signcerts/Admin@org.redeem.merchant.one-cert.pem
    Merchant2:
        mspid: Merchant2MSP
        peers:
            - peer0.org.issue.merchant.two
        certificateAuthorities:
            - ca-Merchant2
        adminPrivateKey:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issue.merchant.two/users/Admin@org.issue.merchant.two/msp/keystore/2608da5208840690044f584baf6e74b700e037a9ea928ee655f3caccc1776160_sk
        signedCert:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issue.merchant.two/users/Admin@org.issue.merchant.two/msp/signcerts/Admin@org.issue.merchant.two-cert.pem
    Merchant3:
        mspid: Merchant3MSP
        peers:
            - peer0.org.issueandredeem.merchant.three
        certificateAuthorities:
            - ca-Merchant3
        adminPrivateKey:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issueandredeem.merchant.three/users/Admin@org.issueandredeem.merchant.three/msp/keystore/f9c209ad0951c4c376675adc0926e931205c1e85a1fba36f09e933e94860ac40_sk
        signedCert:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issueandredeem.merchant.three/users/Admin@org.issueandredeem.merchant.three/msp/signcerts/Admin@org.issueandredeem.merchant.three-cert.pem
orderers:
    orderer0.ordererauthority.organizations:
        url: grpc://hlf-orderer--ordererauthority--orderer0:7050
        gprcOptions:
            ssl-target-name-override: orderer0.ordererauthority.organizations
        tlsCACerts:
            path: artifacts/channel/crypto-config/ordererOrganizations/ordererauthority.organizations/orderers/orderer0.ordererauthority.organizations/tls/ca.crt
peers:
    peer0.org.lead.merchant:
        url: grpc://hlf-peer--leadmerchant--peer0:7051
        gprcOptions:
            ssl-target-name-override: peer0.org.lead.merchant
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.lead.merchant/peers/peer0.org.lead.merchant/tls/ca.crt
    peer0.org.redeem.merchant.one:
        url: grpc://hlf-peer--merchant1--peer0:7051
        gprcOptions:
            ssl-target-name-override: peer0.org.redeem.merchant.one
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.redeem.merchant.one/peers/peer0.org.redeem.merchant.one/tls/ca.crt
    peer0.org.issue.merchant.two:
        url: grpc://hlf-peer--merchant2--peer0:7051
        gprcOptions:
            ssl-target-name-override: peer0.org.issue.merchant.two
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issue.merchant.two/peers/peer0.org.issue.merchant.two/tls/ca.crt
    peer0.org.issueandredeem.merchant.three:
        url: grpc://hlf-peer--merchant3--peer0:7051
        gprcOptions:
            ssl-target-name-override: peer0.org.issueandredeem.merchant.three
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issueandredeem.merchant.three/peers/peer0.org.issueandredeem.merchant.three/tls/ca.crt
certificateAuthorities:
    ca-LeadMerchant:
        url: http://hlf-ca--leadmerchant:7054
        httpOptions:
            verify: 'false'
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.lead.merchant/ca/ca.org.lead.merchant-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        caName: ca-LeadMerchant
    ca-Merchant1:
        url: http://hlf-ca--merchant1:7054
        httpOptions:
            verify: 'false'
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.redeem.merchant.one/ca/ca.org.redeem.merchant.one-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        caName: ca-Merchant1
    ca-Merchant2:
        url: http://hlf-ca--merchant2:7054
        httpOptions:
            verify: 'false'
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issue.merchant.two/ca/ca.org.issue.merchant.two-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        caName: ca-Merchant2
    ca-Merchant3:
        url: http://hlf-ca--merchant3:7054
        httpOptions:
            verify: 'false'
        tlsCACerts:
            path: artifacts/channel/crypto-config/peerOrganizations/org.issueandredeem.merchant.three/ca/ca.org.issueandredeem.merchant.three-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        caName: ca-Merchant3
