NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org.issueandredeem.merchant.three-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org.issueandredeem.merchant.three-cert.pem
    OrganizationalUnitIdentifier: peer
