NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org.issue.merchant.two-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org.issue.merchant.two-cert.pem
    OrganizationalUnitIdentifier: peer
