NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.mydomain.five-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.mydomain.five-cert.pem
    OrganizationalUnitIdentifier: peer
