NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org.redeem.merchant.one-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org.redeem.merchant.one-cert.pem
    OrganizationalUnitIdentifier: peer
